# Generated by Django 5.2 on 2025-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('media_of_origin', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('type_of_media', models.CharField(max_length=100)),
                ('type_of_character', models.CharField(max_length=100)),
                ('backstroy', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
