# Generated by Django 5.2 on 2025-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='media_of_origin',
            new_name='mediaOfOrigin',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type_of_character',
            new_name='typeOfCharacter',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type_of_media',
            new_name='typeOfMedia',
        ),
        migrations.RemoveField(
            model_name='character',
            name='backstroy',
        ),
        migrations.AddField(
            model_name='character',
            name='backstory',
            field=models.TextField(default='No backstory provided'),
        ),
    ]
