# Generated by Django 5.2 on 2025-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_media_of_origin_character_mediaoforigin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(),
        ),
    ]
