# Generated by Django 5.2 on 2025-05-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_media_remove_character_mediaoforigin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='media',
        ),
        migrations.AddField(
            model_name='character',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.media'),
        ),
    ]
