# Generated by Django 5.2 on 2025-05-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_character_media_character_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='typeOfMedia',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.user'),
        ),
    ]
