# Generated by Django 5.2 on 2025-05-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_alter_media_typeofmedia_character_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
