# Generated by Django 5.2 on 2025-05-13 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_logtable_timestamp_monitoredusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredusers',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
