# Generated by Django 5.2 on 2025-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_monitoredusers_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(db_index=True),
        ),
    ]
