import threading
import time
import random
from api.models import Character
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from .views import mock_characters  # Import mock_characters from your view

# Possible values for the character attributes
media_types = ["Books", "Series", "Movie", "Video game"]
character_types = ["Protagonist", "Antagonist", "Deuteragonist", "Confidant", "Love Option"]

def generate_entity_loop():
    while True:
        time.sleep(10)  # wait for 10 seconds before generating a new character

        print("Generating a new character...")
        
        # Generate a random name and other random character details
        name = f"AutoChar{random.randint(1000, 99999)}"
        character = Character.objects.create(
            name=name,
            mediaOfOrigin="Autogen",
            age=random.randint(18, 70),
            typeOfMedia=random.choice(media_types),
            typeOfCharacter=random.choice(character_types),
            backstory="Generated by system",
            image="images/default.png"
        )
        
        # Add the character to the mock_characters list (this is what you wanted)
        mock_characters.append(character)

        # Send to WebSocket group
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            "characters_group",  # The WebSocket group name
            {
                "type": "send_character",  # The method to call on the consumer
                "character": {
                    "name": character.name,
                    "mediaOfOrigin": character.mediaOfOrigin,
                    "age": character.age,
                    "typeOfMedia": character.typeOfMedia,
                    "typeOfCharacter": character.typeOfCharacter,
                    "backstory": character.backstory,
                    "image": character.image
                }
            }
        )
        print("I WANT TO SEND")
        



def start_entity_generator():
    # Start the entity generator in a separate thread
    thread = threading.Thread(target=generate_entity_loop, daemon=True)
    thread.start()
