import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/main/navbar";
import Sidebar from "@/app/main/sidebar";
import { CharacterProvider } from "@/app/types/character"
import { UserProvider } from "./types/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <CharacterProvider>
      <UserProvider>
        <html lang="en" suppressHydrationWarning>
          <body className="h-screen overflow-hidden">
            <div className="flex h-screen">
              {/* Sidebar should stay fixed */}
              <Sidebar />

              {/* Main content area */}
              <div className="flex-1 flex flex-col">
                <Navbar />

                {/* Scrollable content */}
                <main className="flex-1 overflow-auto p-6">
                  <h1 className="text-2xl font-bold mb-4">Fictional Characters</h1>
                  <div className="bg-gray-100 p-4 rounded-lg shadow-md min-h-[80vh] flex flex-col gap-2">
                      {children}
                  </div>
                </main>
              </div>
            </div>
          </body>
        </html>
      </UserProvider>
    </CharacterProvider>
  );
}



